WINDOW_HEIGHT = 640
WINDOW_WIDTH = 960

# Features name
FEATURES_NAME_LIST = [
    'self_x',
    'self_y',
    'oppo_x',
    'oppo_y',
    'players_x_distance',
    'players_y_distance',
    'health_diff',
    'self_front',
    'self_action_id',
    'self_remaining_frames',
    'self_energy',
    'self_health',
    'self_available_action_mask',
    'self_attack_attack_type_id',
    'self_attack_speed_x',
    'self_attack_speed_y',
    'self_attack_hit_damage',
    'self_attack_guard_damage',
    'self_attack_impact_x',
    'self_attack__impact_y',
    'self_attack_x_distance',
    'self_attack_y_distance',
    'self_projectiles_count',
    'self_closest_projectile_to_oppo_type',
    'self_closest_projectile_to_oppo_speed_x',
    'self_closest_projectile_to_oppo_speed_y',
    'self_closest_projectile_to_oppo_hit_damage',
    'self_closest_projectile_to_oppo_guard_damage',
    'self_closest_projectile_to_oppo_impact_x',
    'self_closest_projectile_to_oppo_impact_y',
    'self_closest_projectile_to_oppo_distance_x',
    'self_closest_projectile_to_oppo_distance_y',
    'oppo_front',
    'oppo_action_id',
    'oppo_remaining_frames',
    'oppo_energy',
    'oppo_health',
    'oppo_available_action_mask',
    'oppo_attack_attack_type_id',
    'oppo_attack_speed_x',
    'oppo_attack_speed_y',
    'oppo_attack_hit_damage',
    'oppo_attack_guard_damage',
    'oppo_attack_impact_x',
    'oppo_attack_impact_y',
    'oppo_attack_x_distance',
    'oppo_attack_y_distance',
    'oppo_projectiles_count',
    'oppo_closest_projectile_to_self_type',
    'oppo_closest_projectile_to_self_speed_x',
    'oppo_closest_projectile_to_self_speed_y',
    'oppo_closest_projectile_to_self_hit_damage',
    'oppo_closest_projectile_to_self_guard_damage',
    'oppo_closest_projectile_to_self_impact_x',
    'oppo_closest_projectile_to_self_impact_y',
    'oppo_closest_projectile_to_self_distance_x',
    'oppo_closest_projectile_to_self_distance_y',
    'oppo_is_approaching',
    'self_is_approaching',

    'key_a',
    'key_b',
    'key_c',
    'key_up',
    'key_down',
    'key_left',
    'key_right',
]

